name: test build
on:
  workflow_dispatch:
    inputs:
      test:
        description: "Service Type For AWS"
        required: true
        type: string
env:
  env_test: ${{ inputs.test }}
  LAST_CHILD1: 'L1-1'
  LAST_CHILD2: 'L2-1'
  LAST_CHILD3: 'L3-1'
jobs:
  test_job_name:
    name: test build job
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    env:
      LAST_CHILD2: 'L2-2'
      LAST_CHILD3: 'L3-2'
    steps:
      - uses: actions/checkout@v2
      - name: show node version
        run: node -v
      - name: show branch
        run: git branch
      - name: echo input value
        run: echo "first-'${{ github.event.inputs.test }}'; last- ${{ github.event.inputs }}"
      - name: echo env value
        run: echo "env.env_test->$env_test"
      - name: echo steps env value
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
          LAST_CHILD3: 'L3-3'
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
          echo $LAST_CHILD1 $LAST_CHILD2 $LAST_CHILD3
      - name: check folder
        if: hashFiles('./test-build.yml') != ''
        run: |
          if [[ ! -d "./.github" ]]; then
            echo "文件夹不存在"
          else
            echo "文件夹存在"
          fi
      - name: check folder 2
        if: hashFiles('./.github/workflows/test-build.yml') != ''
        run: |
          if [[ ! -d "./.github" ]]; then
            echo "文件夹不存在"
          else
            echo "文件夹存在"
          fi
      - name: show hash 0
        if: node -v == 'v16.15.0'
        run: echo "success"
      - name: show hash
        run: echo hashFiles('./.github/workflows/test-build.yml')
      - name: show hash 2
        run: hashFiles('./.github/workflows/test-build.yml')