name: test build
on:
  workflow_call:
    inputs:
      test:
       required: true
       type: string
env:
  env_test: ${{ inputs.test }}
jobs:
  test_job_name:
    name: test build job
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test step 2
        run: node -v