name: test build
on:
  workflow_dispatch:
    inputs:
      test:
        description: "Service Type For AWS"
        required: true
        type: string
env:
  env_test: ${{ inputs.test }}
jobs:
  test_job_name:
    name: test build job
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test step 2
        run: node -v
      - name: test step 2
        run: git branch